name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint .
    
    - name: Build Docker image
      run: docker build -t node-app-welcome .

    - name: Log in to ACR
      run: docker login ${{ secrets.ACR_LOGIN_SERVER }} -u "${{ secrets.ACR_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag node-app-welcome:latest ${{ secrets.ACR_LOGIN_SERVER }}/node-app-welcome:latest

    - name: Push Docker image
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/node-app-welcome:latest